import "./globals.css";
import Navbar from "./nav/Navbar";

export const metadata = {
  title: "Live BID",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="container mx-auto px-5 pt-10"></main>
        {children}
      </body>
    </html>
  );
}
